### ISSUE TITLE
(Web) Not using the mouse pointer position to determine the platform location

### ISSUE THREAD

**Issue by 4A6F6F6E61** [Chaduke/paddles_balls_blocks_walls#2]
The Game seems to take the x change values when you move your mouse to move the "platform" location, not the location of the actual mouse pointer.
So, if you move the mouse outside the "walls", the mouse pointer and "platform" have completely different x-values.

**Comment by Chaduke** [comment]
Are you talking about in the web build?  I noticed that in the web version the mouse cursor is not "Captured" like it's done inside the engine.  Basically this means the cursor becomes invisible and is not able to leave the window area behind the scenes. I tried a few different methods in Godot the first day I started working on this and found that going off mouse velocity worked the best, but I had to do - Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)	at the beginning of runtime.  I'll see if I can find out today why this command is not working in the web version.

**Comment by Chaduke** [comment]
Ok so in order to "capture" the mouse cursor on the web, browsers require you to click in the canvas area first. I'm pretty sure the same thing is required to play sound.  I added a "Click to Begin" at the beginning of runtime in order to facilitate this.  When I get time I'll also try to create a separate code path where the paddle is controlled directly by the mouse pointer location, this will be good information to know and give an alternative to those with different mouse setups where using mouse velocity causes issues.  This will also be a good reason to add a main menu with a "Settings" area, which I have planned for this week.

**Comment by Chaduke** [comment]
Hey let me know what you think of the latest update.

**Comment by Chaduke** [comment]
Closing this issue as the game has progressed quite a bit.  Let me know if there's still any kind of issue here.  I haven't noticed any major issues with the mouse lately but since I'm mostly the only one really testing it it's hard to tell what happens on other machines.
